# Copyright Dit 2026
# SPDX-License-Identifier: BUSL-1.1
#
# Validates that all source files carry the required copyright and
# SPDX license headers, using HashiCorp's copywrite tool and the
# repository's .copywrite.hcl configuration. Fails the PR if any
# file is missing its header. To fix locally: `copywrite headers`.
#
name: Copyright Headers

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  copywrite:
    name: Validate License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: Check license headers
        run: copywrite headers --plan
