name: Manual Kernel Build

on:
  workflow_dispatch:
    inputs:
      zfs:
        description: "zfs version"
        required: true
        default: "2.3.4"
      kernel:
        description: "linux kernel"
        required: true
      arch:
        description: "architecture (amd64 or arm64)"
        required: true
        default: "amd64"

permissions:
  contents: read

jobs:
  build_kernel_ubuntu-manual:
    name: Build Kernel (${{ github.event.inputs.zfs }}, ${{ github.event.inputs.kernel }}, ${{ github.event.inputs.arch }})
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout zfs-builder
        uses: actions/checkout@v4
        with:
          repository: datadatdat/zfs-builder
          token: ${{ secrets.GO_MODULES_TOKEN }}
          path: zfs-builder
      - name: Build zfs-builder image
        run: |
          cd zfs-builder
          docker buildx build --platform linux/${{ github.event.inputs.arch }} --load -t datadatdat/zfs-builder:latest .
      - name: Build
        run: ./build -k -b ${{ secrets.s3_bucket }} -a ${{ github.event.inputs.arch }} -z ${{ github.event.inputs.zfs }} ${{ github.event.inputs.kernel }}
      - name: Publish
        run: ./publish ${{ secrets.s3_bucket }}
